# Generated by Django 4.1.1 on 2022-09-15 09:30

import depthQualifier.models
import depthQualifier.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('desc', models.TextField()),
                ('src', models.FileField(upload_to=depthQualifier.models.seq_location, validators=[depthQualifier.validators.validate_archive_extension])),
            ],
        ),
    ]
