# Generated by Django 4.1.1 on 2022-09-16 06:13

import depthQualifier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depthQualifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencemodel',
            name='title',
            field=models.CharField(max_length=30, unique=True, validators=[depthQualifier.models.validate_project_name_exist]),
        ),
    ]
