# Generated by Django 4.1.4 on 2023-01-06 17:36

from django.db import migrations
from django.core.management import call_command

from pathlib import Path

# https://stackoverflow.com/questions/25960850/loading-initial-data-with-django-1-7-and-data-migrations
FIXTURE_FILENAME = 'init_sequences.json'

def load_fixture(apps, schema_editor):
    call_command('loaddata', FIXTURE_FILENAME, app_label='depthQualifier')
    
def unload_fixture(apps, schema_editor):
    # Delete all the elements of Seqeuence model class
    Sequence = apps.get.model('depthQualifier', 'Sequence')
    Sequence.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('depthQualifier', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]