# Generated by Django 4.1.1 on 2022-11-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depthQualifier', '0002_alter_sequencemodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencemodel',
            name='quality',
            field=models.FloatField(null=True),
        ),
    ]
