# Generated by Django 4.1.1 on 2022-11-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depthQualifier', '0004_methodproposal_sequence_seqdepthresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodproposal',
            name='upload_date',
            field=models.DateField(auto_now=True),
        ),
    ]
