# Generated by Django 4.1.1 on 2022-11-25 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depthQualifier', '0005_alter_methodproposal_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seqdepthresults',
            name='method_id',
            field=models.ForeignKey(db_column='method_id', on_delete=django.db.models.deletion.CASCADE, to='depthQualifier.methodproposal'),
        ),
        migrations.AlterField(
            model_name='seqdepthresults',
            name='seq_id',
            field=models.ForeignKey(db_column='seq_id', on_delete=django.db.models.deletion.PROTECT, to='depthQualifier.sequence'),
        ),
    ]
